### ISSUE TITLE
Subscribers cannot be removed

### ISSUE THREAD

**Issue by mmuller** [instedd/remindem#14]
Found in version 1.6.2

Preconditions:
There is a Reminder 'Foo'
The Reminder 'Foo' has a Subscriber '12345'

Steps:
Go to the Subscribers listing of the Reminder 'Foo'
Press the icon to remove the Subscriber '12345'

Obtained:
A '404 Not found page' is shown (http://remindem-stg.instedd.org/en/reminders/34/subscribers/136)

Expected:
The Subscriber should be removed

Additional information:
After pausing the Reminder the Subscriber cannot be removed

![screen shot 2015-03-04 at 12 14 30 pm](https://cloud.githubusercontent.com/assets/518152/6486428/9a90f838-c269-11e4-99e8-090411bff832.png)

**Comment by mmuller** [comment]
Log detail:

ActionController::RoutingError (No route matches [GET] "/en/reminders/34/subscribers/136"):
  actionpack (3.2.21) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.21) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.21) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.21) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.21) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.21) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.21) lib/rails/engine.rb:484:in `call'
  railties (3.2.21) lib/rails/application.rb:231:in `call'
  railties (3.2.21) lib/rails/railtie/configurable.rb:30:in `method_missing'
  /usr/local/rvm/gems/ruby-1.9.3-p484/gems/passenger-4.0.35/lib/phusion_passenger/rack/thread_handler_extension.rb:77:in `process_request'
  /usr/local/rvm/gems/ruby-1.9.3-p484/gems/passenger-4.0.35/lib/phusion_passenger/request_handler/thread_handler.rb:142:in `accept_and_process_next_request'
  /usr/local/rvm/gems/ruby-1.9.3-p484/gems/passenger-4.0.35/lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
  /usr/local/rvm/gems/ruby-1.9.3-p484/gems/passenger-4.0.35/lib/phusion_passenger/request_handler.rb:441:in `block (3 levels) in start_threads'


2015-03-04T17:01:05+0000: [Worker(host:staging.instedd.org pid:30441)] Job SubscribedEvent (id=2) RUNNING
2015-03-04T17:01:05+0000: [Worker(host:staging.instedd.org pid:30441)] Job SubscribedEvent (id=2) FAILED (8 prior attempts) with SocketError: getaddrinfo: Name or service not known
2015-03-04T17:01:05+0000: [Worker(host:staging.instedd.org pid:30441)] 1 jobs processed at 23.6624 j/s, 1 failed

**Comment by mmuller** [comment]
Ok in version 1.6.2
